// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XHotels.Infrastructure;

#nullable disable

namespace XHotels.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230503071047_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("XHotels.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("XHotels.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<int>("NumberOfNights")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoomNumber")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("RoomId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("XHotels.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Floor")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<int>("NumberOfBeds")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoomNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoomType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Floor = 1,
                            IsAvailable = false,
                            IsDeleted = false,
                            NumberOfBeds = 1,
                            PricePerNight = 100m,
                            RoomNumber = 101,
                            RoomType = 1
                        },
                        new
                        {
                            Id = 2,
                            Floor = 2,
                            IsAvailable = false,
                            IsDeleted = false,
                            NumberOfBeds = 2,
                            PricePerNight = 200m,
                            RoomNumber = 201,
                            RoomType = 2
                        },
                        new
                        {
                            Id = 3,
                            Floor = 3,
                            IsAvailable = false,
                            IsDeleted = false,
                            NumberOfBeds = 3,
                            PricePerNight = 300m,
                            RoomNumber = 301,
                            RoomType = 3
                        },
                        new
                        {
                            Id = 4,
                            Floor = 1,
                            IsAvailable = false,
                            IsDeleted = false,
                            NumberOfBeds = 1,
                            PricePerNight = 100m,
                            RoomNumber = 102,
                            RoomType = 1
                        },
                        new
                        {
                            Id = 5,
                            Floor = 2,
                            IsAvailable = false,
                            IsDeleted = false,
                            NumberOfBeds = 2,
                            PricePerNight = 200m,
                            RoomNumber = 202,
                            RoomType = 2
                        },
                        new
                        {
                            Id = 6,
                            Floor = 3,
                            IsAvailable = false,
                            IsDeleted = false,
                            NumberOfBeds = 3,
                            PricePerNight = 300m,
                            RoomNumber = 302,
                            RoomType = 3
                        },
                        new
                        {
                            Id = 7,
                            Floor = 1,
                            IsAvailable = false,
                            IsDeleted = false,
                            NumberOfBeds = 1,
                            PricePerNight = 100m,
                            RoomNumber = 103,
                            RoomType = 1
                        },
                        new
                        {
                            Id = 8,
                            Floor = 2,
                            IsAvailable = false,
                            IsDeleted = false,
                            NumberOfBeds = 2,
                            PricePerNight = 200m,
                            RoomNumber = 203,
                            RoomType = 2
                        },
                        new
                        {
                            Id = 9,
                            Floor = 3,
                            IsAvailable = false,
                            IsDeleted = false,
                            NumberOfBeds = 3,
                            PricePerNight = 300m,
                            RoomNumber = 303,
                            RoomType = 3
                        },
                        new
                        {
                            Id = 10,
                            Floor = 1,
                            IsAvailable = false,
                            IsDeleted = false,
                            NumberOfBeds = 1,
                            PricePerNight = 100m,
                            RoomNumber = 104,
                            RoomType = 1
                        },
                        new
                        {
                            Id = 11,
                            Floor = 2,
                            IsAvailable = false,
                            IsDeleted = false,
                            NumberOfBeds = 2,
                            PricePerNight = 200m,
                            RoomNumber = 204,
                            RoomType = 2
                        },
                        new
                        {
                            Id = 12,
                            Floor = 3,
                            IsAvailable = false,
                            IsDeleted = false,
                            NumberOfBeds = 3,
                            PricePerNight = 300m,
                            RoomNumber = 304,
                            RoomType = 3
                        },
                        new
                        {
                            Id = 13,
                            Floor = 1,
                            IsAvailable = false,
                            IsDeleted = false,
                            NumberOfBeds = 1,
                            PricePerNight = 100m,
                            RoomNumber = 105,
                            RoomType = 1
                        },
                        new
                        {
                            Id = 14,
                            Floor = 2,
                            IsAvailable = false,
                            IsDeleted = false,
                            NumberOfBeds = 2,
                            PricePerNight = 200m,
                            RoomNumber = 205,
                            RoomType = 2
                        },
                        new
                        {
                            Id = 15,
                            Floor = 3,
                            IsAvailable = false,
                            IsDeleted = false,
                            NumberOfBeds = 3,
                            PricePerNight = 300m,
                            RoomNumber = 305,
                            RoomType = 3
                        },
                        new
                        {
                            Id = 16,
                            Floor = 1,
                            IsAvailable = false,
                            IsDeleted = false,
                            NumberOfBeds = 1,
                            PricePerNight = 100m,
                            RoomNumber = 106,
                            RoomType = 1
                        },
                        new
                        {
                            Id = 17,
                            Floor = 2,
                            IsAvailable = false,
                            IsDeleted = false,
                            NumberOfBeds = 2,
                            PricePerNight = 200m,
                            RoomNumber = 206,
                            RoomType = 2
                        },
                        new
                        {
                            Id = 18,
                            Floor = 3,
                            IsAvailable = false,
                            IsDeleted = false,
                            NumberOfBeds = 3,
                            PricePerNight = 300m,
                            RoomNumber = 306,
                            RoomType = 3
                        },
                        new
                        {
                            Id = 19,
                            Floor = 1,
                            IsAvailable = false,
                            IsDeleted = false,
                            NumberOfBeds = 1,
                            PricePerNight = 100m,
                            RoomNumber = 107,
                            RoomType = 1
                        },
                        new
                        {
                            Id = 20,
                            Floor = 2,
                            IsAvailable = false,
                            IsDeleted = false,
                            NumberOfBeds = 2,
                            PricePerNight = 200m,
                            RoomNumber = 207,
                            RoomType = 2
                        },
                        new
                        {
                            Id = 21,
                            Floor = 3,
                            IsAvailable = false,
                            IsDeleted = false,
                            NumberOfBeds = 3,
                            PricePerNight = 300m,
                            RoomNumber = 307,
                            RoomType = 3
                        },
                        new
                        {
                            Id = 22,
                            Floor = 1,
                            IsAvailable = false,
                            IsDeleted = false,
                            NumberOfBeds = 1,
                            PricePerNight = 100m,
                            RoomNumber = 108,
                            RoomType = 1
                        });
                });

            modelBuilder.Entity("XHotels.Models.RoomType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RoomTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Details = "A standard Room with basic amenities",
                            Name = "Standard"
                        },
                        new
                        {
                            Id = 2,
                            Details = "A deluxe Room with luxurious amenities",
                            Name = "Deluxe"
                        },
                        new
                        {
                            Id = 3,
                            Details = "A suite with the best amenities",
                            Name = "Suite"
                        });
                });

            modelBuilder.Entity("XHotels.Models.Reservation", b =>
                {
                    b.HasOne("XHotels.Models.Customer", "Customer")
                        .WithMany("Reservations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("XHotels.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("XHotels.Models.Customer", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
